version: '3'
services:
  tech-challenger:
    build:
      context: ./../tech-challenger
      dockerfile: Dockerfile
    networks:
      - webnet
    expose:
      - "80"

  landing-page:
    build:
      context: ./../tech-challenger-landing
      dockerfile: Dockerfile
    networks:
      - webnet
    expose:
      - "80"

  tech-challenge-back:
    build:
      context: ./../tech-challenge-back
      dockerfile: Dockerfile
    networks:
      - webnet
    expose:
      - "3000"

  nginx:
    image: nginx:alpine
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "3000:3000"
      - "9999:9999"
    depends_on:
      - tech-challenger
      - landing-page
      - tech-challenge-back
    networks:
      - webnet

networks:
  webnet:
    driver: bridge